url: https://badbruce07.github.io
baseurl: /harvest-test-jekyll.github.io/

# Site settings
title: HarvestAPI Main Page

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333


